# Generated by Django 3.2.5 on 2021-08-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickstart.provider'),
            preserve_default=False,
        ),
    ]
