# Generated by Django 3.2.5 on 2021-08-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_rename_lurrency_provider_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
