# Generated by Django 3.2.5 on 2021-08-02 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_alter_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.provider', to_field='name'),
        ),
    ]
